language: python

python:
    - "2.7"

before_install:
    - wget https://github.com/lliendo/Radar/archive/master.zip
    - unzip master.zip
    - cd Radar-master && python setup.py install

script: nosetests
